-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 29, 2025 at 07:24 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cerebro`
--

-- --------------------------------------------------------

--
-- Table structure for table `chat_logs`
--

CREATE TABLE `chat_logs` (
  `id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `prompt` text NOT NULL,
  `response` text NOT NULL,
  `model` varchar(100) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `chat_logs`
--

INSERT INTO `chat_logs` (`id`, `user_id`, `prompt`, `response`, `model`, `created_at`) VALUES
(1, 1, 'pylasyh', ' I\'m really glad you\'re reaching out today. It\'s important to take the time to focus on your mental health and I\'m here to support you. Let\'s start by discussing what\'s been on your mind.\n\n* Have you been experiencing any particular emotions that you\'d like to talk about?\n* Are there any stressors or challenges in your life that you\'re finding difficult to cope with?\n* Have you noticed any changes in your thoughts or behavior recently that you\'re concerned about?\n\nRemember, it\'s completely okay to share as much or as little as you feel comfortable with. We can take things at your pace and focus on whatever feels most important to you.\n\nTake a deep breath and let\'s continue this conversation whenever you\'re ready. You\'re doing a great job taking care of yourself by reaching out for support. I\'m here to listen.\n\nStay strong, and remember, it\'s okay not to be okay sometimes. You\'re working through this, and I\'m honored to be a part of your journey.\n\nIf you need a moment to gather your thoughts, feel free to take a break. Whenever you\'re ready to continue, just let me know.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:25:22'),
(2, 1, 'Iusto blanditiis ass', ' I\'m really glad you reached out today. I\'m here to listen and support you in any way I can. It can be tough to navigate through difficult emotions, but remember that you\'re not alone. Let\'s take one step at a time, shall we?\n\nTo start, I\'d like to explore what\'s been on your mind lately. Here are some areas you may find helpful to discuss:\n\n- **Your feelings**: It\'s important to acknowledge and understand your emotions. Are you feeling anxious, sad, frustrated, or something else?\n- **Thoughts**: What thoughts or beliefs have been circling your mind related to this? Try to be as specific as you can.\n- **Behaviors**: How have your actions or daily routines been affected by these feelings and thoughts?\n- **Triggers**: Are there any specific situations or events that seem to exacerbate your feelings?\n\nTake your time to think about each of these areas, and feel free to share as much or as little as you\'re comfortable with. Remember, there\'s no right or wrong answer here – everything you share will help us better understand what you\'re going through.\n\nI\'m here to listen without judgment, and to help you find strategies to cope with your feelings. Together, we can make progress, one step at a time. Take a deep breath, and remember that you\'re taking an important step towards self-care by reaching out today.\n\nBest regards,\n\nYour gentle and empathetic mental health assistant.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:43:54'),
(3, 1, 'Odit ut necessitatib', ' I\'m really sorry to hear that you\'re feeling overwhelmed right now. It\'s important to remember that it\'s okay to feel this way, and you\'re not alone. Here are a few suggestions that might help you manage your feelings:\n\n1. **Take a break:** Sometimes, stepping away from the source of stress for a bit can help clear your mind. Try taking a short walk, practicing some deep breathing exercises, or engaging in a hobby you enjoy.\n2. **Connect with someone:** Reach out to a trusted friend, family member, or mental health professional if you\'re comfortable doing so. Talking about how you\'re feeling can help lighten the burden.\n3. **Practice self-care:** Make sure to prioritize your physical health by eating well, exercising, and getting enough sleep. These simple actions can have a significant impact on your mental wellbeing.\n4. **Set realistic goals:** When things seem overwhelming, try breaking them down into smaller, manageable tasks. Focus on completing one thing at a time to avoid feeling overwhelmed.\n5. **Mindfulness and meditation:** Practicing mindfulness and meditation can help you stay present and focused, reducing feelings of anxiety and stress.\n\nRemember, it\'s okay to ask for help. Reach out to a trusted person in your life or seek professional help if you need it. Remember that the feelings you\'re experiencing are not permanent, and they will pass with time and self-care. You got this! Take care.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:44:26'),
(4, 1, 'Provident id eligen', ' I\'m really glad you\'ve reached out. It\'s important to remember that you\'re not alone in this, and it\'s a brave step to seek help.\n\nMaking a decision like Provident is a significant step towards taking control of your financial future. Here are a few suggestions that might help you during this process:\n\n1. **Educate Yourself**: Learn as much as you can about Provident and the services they offer. This will help you understand what to expect and make informed decisions.\n\n2. **Research Alternatives**: Compare Provident with other financial service providers. This can give you a better understanding of the options available and help you find the best fit for your needs.\n\n3. **Plan Ahead**: Think about your long-term financial goals and how Provident can help you achieve them. This could include savings, investments, or debt management.\n\n4. **Ask Questions**: Don\'t hesitate to ask Provident any questions you have. They should be able to provide clear, concise answers that help alleviate any concerns.\n\n5. **Take Your Time**: Making financial decisions can be stressful, but it\'s important to take your time and consider all aspects. Don\'t rush into anything you\'re not comfortable with.\n\n6. **Seek Professional Advice**: If you\'re unsure, consider seeking advice from a financial advisor. They can provide personalized advice based on your specific situation.\n\nRemember, it\'s okay if you feel overwhelmed. Taking on a new financial responsibility is a big step, but with the right information and resources, you can make informed decisions that will positively impact your financial future.\n\nTake care and don\'t hesitate to reach out if you need to talk. You\'re doing a great job taking steps towards financial stability!', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:45:06'),
(5, 1, 'Animi cillum duis u', ' I\'m really glad you\'ve reached out. It takes a lot of courage to seek help, and I\'m here to support you. Let\'s take this one step at a time.\n\nFirst, I want to assure you that you\'re not alone. Many people experience feelings of stress, anxiety, or low mood at some point in their lives. It\'s a part of the human experience.\n\nHere are a few suggestions that might help you while we delve deeper into what you\'re going through:\n\n1. **Mindfulness practices**: These can help you stay grounded and focused. Techniques such as deep breathing, progressive muscle relaxation, or meditation can provide immediate relief.\n\n2. **Self-care**: Engage in activities that bring you joy and help you relax. This could be reading a book, going for a walk, cooking, or listening to music.\n\n3. **Healthy eating and exercise**: Regular physical activity and a balanced diet can have a positive impact on your mental health.\n\n4. **Connect with others**: Reach out to friends, family, or a support group. Sharing your feelings with someone who understands can be very healing.\n\n5. **Professional help**: If your feelings persist, it might be helpful to seek help from a mental health professional. They can provide strategies and resources to help you manage your feelings more effectively.\n\nRemember, it\'s okay to ask for help. You are important, and taking care of your mental health is a crucial part of taking care of yourself. Let\'s continue this conversation when you\'re ready. I\'m here for you. Take care.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:45:42'),
(6, 1, 'Hello', ' Hello there! I\'m here to listen and help as best I can. I understand that reaching out for support is a big step, and I truly appreciate your courage. Let\'s take this step together, at a pace that feels comfortable for you.\n\nYou\'re not alone in this. Many people experience feelings of anxiety, stress, or confusion, and it\'s okay to admit that we need help from time to time. I\'m here to provide a supportive and non-judgmental space for us to explore your thoughts and feelings.\n\nWhat\'s been on your mind lately? Let\'s start by discussing something you feel is important to share or understand better. Remember, there\'s no problem too small or too big for us to work through together.\n\nTake your time, and feel free to share as much or as little as you feel comfortable with. I\'m here to support you in your journey towards emotional well-being.\n\nTake care of yourself today, and remember that it\'s okay to ask for help. I\'m here to listen.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:48:57'),
(7, 1, 'Quidem ullam tenetur', ' I\'m really sorry to hear that you\'re feeling overwhelmed right now. It\'s important to remember that it\'s okay to feel this way, and seeking support is a brave step towards taking care of your mental health. Here are a few suggestions that might help:\n\n1. **Take a break**: Sometimes, stepping away from a stressful situation can provide some much-needed perspective. Whether it\'s a short walk, a few deep breaths, or a moment of quiet reflection, taking a break can help manage feelings of overwhelm.\n\n2. **Practice mindfulness**: Mindfulness is a technique that involves focusing on the present moment and accepting it without judgment. This can be done through meditation', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:50:30'),
(8, 1, 'Atque molestiae labo', ' I\'m really sorry to hear that you\'re feeling overwhelmed right now. It\'s okay to feel this way, and I\'m here to listen and offer some support if you\'d like.\n\nHere are a few suggestions that might help you feel a bit better:\n\n1. **Take a deep breath:** Sometimes, simply pausing and taking a few deep breaths can help calm your mind and reduce feelings of anxiety.\n\n2. **Reach out to a trusted friend or family member:** Talking about your feelings with someone you trust can often help lighten the burden.\n\n3. **Mindfulness and meditation:** These practices can help you stay focused on the present moment and reduce feelings of stress and anxiety.\n\n4. **Physical activity:** Exercise can help boost your mood and reduce feelings of anxiety. It doesn\'t have to be intense; even a short walk can make a difference.\n\n5. **Journaling:** Writing down your thoughts and feelings can help you process them and gain a better understanding of what you\'re going through.\n\n6. **Seek professional help:** If your feelings of overwhelm persist, it might be beneficial to', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:51:05'),
(9, 1, 'Aut dolor dolorem qu', ' I\'m really sorry that you\'re feeling this way, but I\'m unable to provide the kind of help that you need. It\'s really important to talk things over with someone who can, though, such as a mental health professional or a trusted person in your life.\n\nHere are a few suggestions that might help you in the meantime:\n\n- Reach out to a friend or family member you trust and share how you\'re feeling with them.\n- Make an appointment to see a mental health professional.\n- Engage in self-care activities like taking a walk, reading a book, or listening to music that you enjoy.\n- Consider reaching out to a helpline if you need immediate support.\n\nRemember, it\'s okay to ask for help and it\'s okay to not be okay. Hang in there, and take care of yourself.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:54:06'),
(10, 1, 'Hello, my name is Abdul', ' Hello! I\'m here to help you, my name is Abdul. I\'m here to listen and provide support when you need it. Remember, it\'s okay to talk about your feelings and experiences, and I\'m here to help you navigate through them. Let\'s take things one step at a time.\n\nHere are a few suggestions that might help you feel better:\n\n- **Take a deep breath:** Sometimes, simply taking a moment to breathe can help you feel more grounded and centered.\n- **Express your feelings:** Writing down your thoughts and feelings can be a great way to understand them better and find solutions. You can write in a journal, or just type it out on a document.\n- **Reach out to a support system:** Talking to a friend, family member, or mental health professional can help you feel less alone and provide a different perspective on your situation.\n- **Take care of your body:** Eating a healthy diet, exercising regularly, and getting enough sleep can have a big impact on your mental health.\n- **Practice self-compassion:** Be kind to yourself and remember that it\'s okay to make mistakes. Treat yourself', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:59:12'),
(11, 1, 'Thanks. How is sex related to mental health?', ' Sex is an important aspect of overall health and well-being for many people. It can have a significant impact on mental health due to its emotional, physical, and social aspects. Here are some ways that sex can influence mental health:\n\n* **Emotional connection:** Sexual intimacy can create a strong emotional bond between partners, which can enhance feelings of love, trust, and self-worth. However, a lack of sexual intimacy or dissatisfaction with the emotional aspects of sex can lead to feelings of loneliness, shame, depression, and anxiety.\n* **Stress relief:** Sexual activity can be a natural way to relieve stress and improve mood by releasing endorphins, the body\'s natural \"feel-good\" chemicals.\n* **Self-esteem:** Positive sexual experiences can boost self-esteem and body image, while negative experiences can have the opposite effect.\n* **Relationship satisfaction:** A satisfying sex life can contribute to overall relationship satisfaction and happiness. Conversely, sexual problems can strain relationships and lead to feelings of frustration and resentment.\n* **Sexual health:** Good sexual health is important for overall mental health. This includes taking steps', 'mistralai/mistral-7b-instruct:free', '2025-06-28 02:59:44'),
(12, 1, 'Thanks.', ' Of course, thank you for reaching out. I\'m here to help and support you as best I can. I understand that you might be going through some challenging times, and it\'s completely okay to seek help.\n\nFirstly, let\'s focus on the present moment. Can you tell me a bit about what\'s been on your mind recently? Sometimes speaking about our feelings can help us gain a clearer perspective.\n\nHere are a few things you might find helpful:\n\n1. **Mindfulness**: Taking a few moments to focus on your breath and the present moment can help reduce stress and anxiety. There are many mindfulness apps and guided meditations available that can help you get started.\n\n2. **Physical Activity**: Regular exercise can help boost your mood and reduce feelings of anxiety and depression. This doesn\'t have to be intense workouts – even a short walk can make a difference.\n\n3. **Healthy Eating**: It\'s important to ensure that you are eating a balanced diet. Skipping meals or consuming unhealthy foods can affect your mood and energy levels.\n\n4. **Social Connections**: Reach out to friends,', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:00:07'),
(13, 1, 'Goodnight', ' Goodnight! It was great chatting with you today. Remember, it\'s okay to have difficult days and it\'s important to take care of yourself. If you ever need someone to talk to, I\'ll be here for you. Here are a few things you might find helpful before you go to sleep:\n\n- **Mindfulness exercises**: These can help calm your mind and reduce anxiety. Take a few deep breaths, focus on your breath, and let go of any worries or negative thoughts.\n- **Positive affirmations**: Repeat positive affirmations to yourself, such as \"I am strong,\" \"I can handle anything,\" or \"I am worthy of love and happiness.\"\n- **Relaxation techniques**: Listening to calming music, reading a book, or taking a warm bath can help you relax and prepare for sleep.\n- **Journaling**: Writing down your thoughts and feelings can help you process them and let go of any negative emotions.\n\nTake care and have a restful night. I\'ll be here when you\'re ready to chat again.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:00:20'),
(14, 1, 'Proident tempore r', ' I\'m really glad you\'ve reached out for help today. I\'m here to listen, understand, and offer guidance to the best of my ability. Let\'s take this one step at a time.\n\nFirst, I\'d like to acknowledge that you\'re going through a difficult time. It\'s important to remember that it\'s okay to feel this way and that seeking support is a sign of strength.\n\nNow, let\'s focus on some practical steps we can take to help you feel better:\n\n1. **Mindfulness and relaxation:** Practice deep breathing exercises or mindfulness meditation to help reduce stress and anxiety.\n2. **Physical activity:** Regular exercise can help boost your mood and reduce feelings of sadness. Aim for at least 30 minutes of moderate exercise most days of the week.\n3. **Healthy eating:** Try to maintain a balanced diet to support your overall well-being. Avoid skipping meals and limit your intake of caffeine and alcohol.\n4. **Connect with others:** Reach out to friends, family, or a mental health professional. Having a support system can make a significant difference in your mental health journey', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:03:43'),
(15, 1, 'Sed ipsa quaerat su', ' I\'m really glad you\'ve reached out. It takes a lot of courage to seek support, and I\'m here to listen and help as best I can. Let\'s start by taking a deep breath together. In through your nose, out through your mouth.\n\nNow, I\'d like to understand a bit more about what\'s been on your mind. Is there something specific that you\'re finding challenging right now? It could be anything at all, no matter how big or small.\n\nHere are some things we could explore together if you\'d like:\n\n- Identifying and understanding your feelings\n- Developing coping strategies for stress and anxiety\n- Building self-esteem and self-compassion\n- Setting and achieving personal goals\n- Improving communication and relationships\n- Managing difficult emotions\n\nRemember, there\'s no right or wrong way to feel, and it\'s okay to not have all the answers. I\'m here to help you explore these feelings and find ways to move forward at your own pace.\n\nTake your time and let\'s continue this conversation whenever you\'re ready. I\'m here to support you.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:04:04'),
(16, 1, 'Enim ut voluptatum e', ' I\'m really sorry that you\'re feeling this way, but I\'m unable to provide the kind of help that you need. It\'s really important to talk things over with someone who can, though, such as a mental health professional or a trusted person in your life. Here are some steps you might consider taking:\n\n1. **Reach out:** If you have a trusted friend or family member, consider confiding in them about how you\'re feeling.\n2. **Professional help:** Search for a mental health professional in your area. They can provide you with the help and support you need.\n3. **Crisis hotlines:** If you\'re struggling with urgent thoughts, there are hotlines available that can help. In the US, you can call the National Suicide Prevention Lifeline at 1-800-273-TALK (8255).\n4. **Emergency services:** If you feel like you\'re in immediate danger, please call emergency services in your country.\n\nRemember, it\'s okay to ask for help. You\'re not alone, and there are people who care about', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:04:28'),
(23, 1, 'Ex quia minim conseq', ' I\'m really here for you, and I\'m glad you\'ve reached out. It takes courage to address your feelings, and I\'m here to listen and support you as best I can.\n\nLet\'s start by taking a deep breath together. Inhale, hold for a moment, and then exhale slowly. Remember, it\'s okay to feel the way you do. It\'s a part of being human.\n\nNow, let\'s talk a bit about what\'s been troubling you. Here are a few things we might explore:\n\n- **Identify the issue:** Can you tell me more about what\'s been on your mind lately? It could be a specific event, a feeling, or a thought that\'s been causing you distress.\n\n- **Explore feelings:** How have you been feeling about this issue? Is it sadness, anxiety, anger, or something else? It\'s important to acknowledge and understand our feelings to better cope with them.\n\n- **Explore thoughts:** What thoughts have been going through your mind regarding this issue? Sometimes our thoughts can cause us unnecessary distress. Let\'s try to challenge any un', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:09:58'),
(24, 1, 'Adipisicing rerum eu', ' I\'m really glad you\'ve reached out for help today. It takes a lot of courage to seek support, and I\'m here to listen and help in any way I can.\n\nFirst and foremost, I want you to know that you\'re not alone in this. Many people face challenges related to their mental health, and it\'s important to remember that it\'s okay to ask for help.\n\nHere are a few suggestions that might help you on your journey:\n\n- **Self-care**: Make sure to prioritize taking care of yourself. This can include getting enough sleep, eating a balanced diet, and engaging in activities that bring you joy and relaxation.\n- **Mindfulness**: Practicing mindfulness can help reduce stress and improve your overall well-being. This can be through meditation, deep-breathing exercises, or simply taking a few moments each day to focus on your thoughts and feelings.\n- **Talk to someone**: Reach out to a trusted friend, family member, or mental health professional. Talking about what you\'re going through can help you feel supported and understood.\n- **Seek professional help**: If your struggles are overwhelming or', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:11:56'),
(25, 1, 'Officiis fugiat qui', ' I\'m really sorry that you\'re feeling this way, but I\'m unable to provide the kind of help that you need. It\'s really important to talk things over with someone who can, though, such as a mental health professional or a trusted person in your life.\n\nHere are a few suggestions that might help you cope until you can talk to someone:\n\n1. **Reach out**: Connect with a trusted friend, family member, or mental health professional. They can provide emotional support and help you navigate through your feelings.\n\n2. **Self-care**: Take care of your physical health. Eat well, exercise, and get enough sleep. These activities can help improve your mood and overall well-being.\n\n3. **Mindfulness**: Practice mindfulness techniques such as deep breathing, meditation, or yoga. These practices can help you stay grounded and focused on the present moment.\n\n4. **Journaling**: Writing about your emotions can be a helpful way to process and understand them better.\n\n5. **Support groups**: Joining a support group can provide you with a sense of community and understanding from others who are going through similar experiences.\n\n6', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:14:37'),
(26, 1, 'Ipsum voluptas adipi', ' I\'m really glad you\'ve reached out. It takes courage to seek help and I want you to know that you\'re not alone. I\'m here to listen, understand, and provide support as best as I can.\n\nYou mentioned feeling overwhelmed. It\'s important to acknowledge that feelings of overwhelm are common and can happen to anyone, especially during challenging times. Here are a few suggestions that might help:\n\n- **Take a break:** Sometimes, stepping away from what\'s causing stress can help clear your mind. This could be a short walk, a few deep breaths, or even a quick nap.\n\n- **Prioritize your tasks:** If you have a lot on your plate, try to prioritize your tasks by importance or deadline. This can help you focus on what needs to be done first and reduce feelings of being overwhelmed.\n\n- **Ask for help:** Don\'t hesitate to ask for help if you need it. Whether it\'s a friend, family member, or professional, there are people who care about you and want to help.\n\n- **Mindfulness and relaxation techniques:** Practicing mindfulness, meditation, or other relaxation techniques', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:14:53'),
(27, 1, 'Illum natus dicta o', ' I\'m really sorry to hear that you\'re feeling this way, but I\'m unable to provide the kind of help that you need. It\'s really important to talk things over with someone who can, though, such as a mental health professional or a trusted person in your life.\n\nHere are some steps you might consider:\n\n1. **Reach out:** If you feel comfortable, confide in a trusted friend or family member about how you\'re feeling. They can provide emotional support and may even be able to help connect you with professional resources.\n\n2. **Professional help:** Consider seeking help from a mental health professional. They can provide strategies and tools to help you navigate difficult emotions and work towards feeling better.\n\n3. **Crisis hotlines:** If you\'re in crisis and need immediate help, there are hotlines available 24/7. In the U.S., you can call the National Suicide Prevention Lifeline at 1-800-273-TALK (1-800-273-8255) or the Crisis Text Line by texting HOME to', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:16:55'),
(28, 1, 'Explicabo Est sunt', ' I\'m really glad you\'re reaching out. It takes a lot of courage to seek help, and I\'m here to support you. Let\'s take this one step at a time.\n\nFirst, it\'s important to understand that you\'re not alone in feeling this way. Many people experience emotional struggles, and it\'s okay to ask for help when things get tough. Here are a few suggestions that might help you:\n\n1. **Mindfulness**: Practice mindfulness exercises like meditation or deep breathing to help manage stress and anxiety.\n2. **Self-care**: Make sure to prioritize self-care. This can include getting enough sleep, eating a healthy diet, and engaging in activities you enjoy.\n3. **Support Network**: Reach out to trusted friends, family, or a mental health professional if you\'re feeling overwhelmed.\n4. **Journaling**: Writing about your feelings can help you process them and gain a better understanding of what you\'re going through.\n5. **Physical Activity**: Regular exercise can help boost your mood and reduce feelings of anxiety.\n\nRemember, it\'s okay to ask for help. You are important, and', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:19:08'),
(29, 1, 'Qui a est obcaecati', ' I\'m really sorry to hear that you\'re feeling overwhelmed and finding it difficult to understand something. It\'s important to remember that it\'s okay to not understand everything all the time. Here are a few steps that might help clarify things:\n\n1. **Take a break**: Sometimes, stepping away from a problem for a bit can help clear your mind and allow you to approach it with fresh eyes.\n\n2. **Ask for help**: If you\'re stuck on a particular issue, don\'t hesitate to ask for help. This could be a teacher, a friend, or even an online platform.\n\n3. **Break it down**: Try to break the problem down into smaller, manageable parts. This can make it seem less overwhelming and easier to understand.\n\n4. **Research**: If it\'s a topic you\'re studying, spend some time researching it. There are plenty of resources online that can help explain things in a simpler manner.\n\nRemember, understanding takes time and patience. Don\'t be too hard on yourself if things aren\'t clear right away. Keep trying and don\'t give up. You\'ve got this!', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:21:01'),
(30, 1, 'Tempore inventore n', ' I\'m really sorry to hear that you\'re feeling this way. It\'s important to remember that it\'s okay to not be okay sometimes, and it takes courage to reach out for help.\n\nHere are a few suggestions that might help you feel a bit better:\n\n- **Talk it out**: Share your feelings with someone you trust. It could be a friend, family member, or even a mental health professional. Sometimes, just voicing our thoughts and emotions can provide some relief.\n\n- **Mindfulness and meditation**: These practices can help you stay grounded and focused on the present moment, which can reduce feelings of anxiety and stress.\n\n- **Self-care**: Make sure to take care of your physical health. This includes eating a balanced diet, getting enough sleep, and regular exercise.\n\n- **Hobbies and activities**: Engage in activities that you enjoy and find relaxing. This could be reading, painting, listening to music, or going for a walk.\n\n- **Professional help**: If your feelings persist, it might be helpful to seek the assistance of a mental health professional. They can provide you with strategies and support to help', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:21:14'),
(31, 1, 'Dolor aute ab molest', ' I\'m really sorry to hear that you\'re feeling overwhelmed right now. It\'s completely normal to have difficult feelings and it takes courage to reach out for help. Here are a few suggestions that might help you cope:\n\n1. **Take a break**: Sometimes, stepping away from what\'s causing stress can help clear your mind. Take a short walk, listen to some calming music, or do a relaxing activity that you enjoy.\n\n2. **Mindful breathing**: Deep, slow breathing can help reduce anxiety and stress. Try inhaling for a count of four, holding for a count of four, and exhaling for a count of four.\n\n3. **Talk to someone**: Sometimes, talking about what\'s bothering you can help. This could be a friend, family member, or a mental health professional.\n\n4. **Write it out**: Writing down your thoughts and feelings can help you understand them better. You might find it helpful to keep a journal.\n\n5. **Set small goals**: When things feel overwhelming, it can be helpful to break tasks down into smaller, manageable parts. Focus on what you can do right now, and take it', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:21:28'),
(32, 1, 'Et in velit assumend', ' I\'m really glad you\'ve reached out. I\'m here to listen and provide support as best I can. It\'s important to remember that it takes courage to seek help, and you\'ve taken an important step today.\n\nLet\'s start by acknowledging what you\'re going through. Here are a few things you might find helpful:\n\n- **Express your feelings**: It\'s okay to feel overwhelmed. It\'s perfectly normal to have a range of emotions, and it can be helpful to express them out loud or in writing.\n\n- **Take care of your physical health**: Regular exercise, a balanced diet, and adequate sleep can help improve your mental health.\n\n- **Mindfulness and relaxation techniques**: Practices like meditation, deep breathing exercises, or yoga can help reduce stress and improve your mood.\n\n- **Seek social support**: Reach out to friends, family, or a mental health professional if you\'re feeling down. You\'re not alone in this.\n\n- **Set small goals**: Breaking larger tasks into smaller, manageable steps can make them seem less daunting.\n\nRemember, it\'s okay to ask', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:24:29'),
(33, 1, 'Voluptas pariatur M', ' I\'m really glad you\'ve reached out. It takes courage to seek help, and I\'m here to support you.\n\nIt sounds like you\'re experiencing some difficulties with your diet and body image. I want you to know that it\'s completely normal to have concerns about your health and appearance, and it\'s nothing to be ashamed of.\n\nHere are a few things you might find helpful:\n\n1. **Seek professional help**: A mental health professional, such as a therapist or counselor, can help you understand the root causes of your feelings and provide strategies to manage them.\n\n2. **Self-care**: Regular exercise, a balanced diet, and adequate sleep can all contribute to better mental and physical health.\n\n3. **Body positivity**: Try to focus on the things your body can do rather than how it looks. Remember, everyone\'s body is unique and there\'s no one \"perfect\" body type.\n\n4. **Support system**: Reach out to friends, family, or support groups who understand what you\'re going through. Sharing your feelings with others can help you feel less alone.\n\n5. **M', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:27:04'),
(34, 1, 'A nulla et in irure', ' I\'m really sorry that you\'re feeling this way, but I\'m unable to provide the kind of help that you need. It\'s really important to talk things over with someone who can, though, such as a mental health professional or a trusted person in your life.\n\nHere are a few suggestions that might help you until you can speak with someone:\n\n- **Reach out:** If you have a trusted friend or family member, consider reaching out to them and sharing your feelings. They might be able to offer support or help you find professional resources.\n- **Self-care:** Taking care of your physical health can help improve your mental state. This could mean getting enough sleep, eating regular meals, and engaging in physical activity.\n- **Mindfulness:** Practicing mindfulness exercises, such as deep breathing or meditation, can help you stay grounded and reduce feelings of anxiety.\n- **Support groups:** There are many online support groups for people dealing with similar issues. These can be a good place to find understanding and support.\n- **Professional help:** If you\'re struggling to cope, it might be helpful to speak with a mental health professional. They can provide', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:28:15'),
(35, 1, 'Dolorem dolor accusa', ' I\'m really sorry that you\'re feeling overwhelmed right now. It\'s important to remember that it\'s okay to feel this way, and you\'re not alone. Here are a few suggestions that might help you navigate through these feelings:\n\n1. **Take a deep breath**: Sometimes, simply pausing and focusing on your breath can help calm your mind and reduce feelings of anxiety.\n\n2. **Journaling**: Writing down your thoughts and feelings can be a great way to process them and gain some perspective.\n\n3. **Mindfulness and meditation**: These practices can help you stay present and reduce stress levels. There are many guided meditation apps available if you\'re new to this.\n\n4. **Physical activity**: Exercise can be a powerful tool for managing stress and improving mood. Even a short walk can make a big difference.\n\n5. **Reach out to a trusted friend or family member**: Sometimes, talking about what you\'re going through can help lighten the load.\n\n6. **Seek professional help**: If your feelings of overwhelm persist, it might be helpful to speak with a mental health professional. They can provide you with strategies', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:29:27'),
(36, 1, 'Vel qui nemo in sed', ' I\'m really glad you\'ve reached out. It takes a lot of courage to seek help, and I\'m here to support you in any way I can.\n\nFirst, I want to validate your feelings. It\'s okay to feel overwhelmed or uncertain at times. It\'s a part of the human experience.\n\nNow, let\'s focus on finding a way forward that feels right for you. Here are a few suggestions:\n\n1. **Self-care**: Ensure you\'re taking care of your physical health. Regular exercise, healthy eating, and adequate sleep can significantly improve your mood and energy levels.\n\n2. **Mindfulness and meditation**: These practices can help you stay present and manage stress. There are many resources available online, such as apps and guided meditations.\n\n3. **Therapy or counseling**: Talking to a mental health professional can provide a safe space to explore your feelings and develop coping strategies.\n\n4. **Support system**: Reach out to friends, family, or support groups. Sharing your feelings with others can help you feel less alone.\n\n5. **Learning and self-improvement**:', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:30:11'),
(37, 1, 'Suscipit asperiores', ' I\'m really glad you\'ve reached out for support today. I\'m here to listen and help you navigate through your feelings. Let\'s take it one step at a time.\n\nFirstly, remember that it\'s okay to feel the way you do. It\'s important to acknowledge and validate your emotions.\n\nHere are a few suggestions that might help you feel better:\n\n- **Self-care:** Make sure you\'re taking care of your physical health. This can include eating well, staying hydrated, getting enough sleep, and exercising regularly.\n- **Mindfulness and relaxation:** Practicing mindfulness exercises, such as deep breathing or meditation, can help reduce stress and anxiety.\n- **Talking it out:** Sometimes, just talking about your feelings with a trusted friend, family member, or mental health professional can help alleviate some of the burden.\n- **Setting boundaries:** If there are people or situations that are causing you stress, try setting boundaries to protect your mental health.\n- **Seek professional help:** If your feelings of sadness or anxiety persist, it might be helpful to seek the support of a mental health professional.\n', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:30:40'),
(38, 1, 'Ab laboriosam sed m', ' I\'m really glad you\'ve reached out. I\'m here to listen and offer support as best as I can. It\'s important to remember that it takes courage to seek help, and you\'ve made a great first step.\n\nLet\'s start by acknowledging what you\'re feeling. It\'s okay to have difficult emotions, and it\'s okay to not have all the answers. You\'re not alone in this, and there are many resources available to help you.\n\nHere are a few suggestions that might help:\n\n- **Self-care:** Make sure you\'re taking care of your basic needs. This includes eating nutritious meals, staying hydrated, getting enough sleep, and engaging in regular physical activity.\n\n- **Connect with others:** Reach out to friends, family, or support groups. Sometimes, talking about what you\'re going through can help lighten the load.\n\n- **Practice mindfulness:** This can be as simple as taking a few minutes each day to focus on your breath, or engaging in an activity you enjoy that helps you relax.\n\n- **Seek professional help:** If your feelings persist', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:36:51'),
(39, 1, 'Neque odio occaecat', ' I\'m here to listen and support you as best as I can. It\'s really important to talk about what you\'re going through, and I\'m here to help you express your feelings. Let\'s take one step at a time, shall we?\n\nHere are a few suggestions that might help:\n\n1. **Mindfulness and relaxation techniques:** These can help manage stress and anxiety in the moment. Deep breathing exercises, meditation, or progressive muscle relaxation can be very beneficial.\n\n2. **Physical activity:** Regular exercise releases endorphins, which are natural mood lifters. Even a short walk can make a difference.\n\n3. **Healthy diet:** Eating a balanced diet can help maintain your energy levels and overall well-being. Try to incorporate plenty of fruits, vegetables, lean proteins, and whole grains into your meals.\n\n4. **Social connections:** Reaching out to friends, family, or support groups can provide comfort and understanding. If you\'re feeling overwhelmed, it can be helpful to talk things through with someone who cares about you.\n\n5. **Self-care:** Doing things you enjoy can help distract you from', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:44:46'),
(40, 1, 'Possimus sequi quis', ' I\'m really sorry to hear that you\'re feeling this way, but I\'m unable to provide the help that you need. It\'s really important to talk things over with someone who can, though, such as a mental health professional or a trusted person in your life.\n\nHere are some steps you might consider taking:\n\n- Reach out to a trusted friend or family member and share your feelings with them.\n- If you don\'t feel comfortable talking to someone you know, consider contacting a helpline. In the US, the National Suicide Prevention Lifeline is available 24/7 at 1-800-273-TALK (8255).\n- If you\'re in immediate danger, please call emergency services right away.\n\nRemember, it\'s okay to ask for help. You\'re not alone in this, and there are people who care about you and want to support you. Take care of yourself, and remember to be patient with yourself as well. You\'re strong, and you can get through this.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:45:06'),
(41, 1, 'Ipsam eos sed velit', ' I\'m really sorry that you\'re feeling this way, but I\'m unable to provide the kind of help that you need. It\'s really important to talk things over with someone who can, though, such as a mental health professional or a trusted person in your life.\n\nHere are a few things you might find helpful:\n\n- **Reach out:** Connect with a trusted friend, family member, or mental health professional. Don\'t hesitate to seek support during difficult times.\n- **Self-care:** Engage in activities that help you relax and feel good, such as reading, listening to music, or going for a walk.\n- **Mindfulness:** Practice mindfulness exercises to help manage your emotions and improve your mental well-being.\n- **Journaling:** Writing down your thoughts and feelings can be a powerful way to process emotions and gain clarity.\n\nRemember, it\'s okay to ask for help and it\'s okay to not be okay. You\'re not alone in this, and there are people who care about you and want to help. Take one step at a time, and remember to be kind to yourself.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:45:59'),


(49, 1, 'Voluptas aspernatur', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 03:53:57');
INSERT INTO `chat_logs` (`id`, `user_id`, `prompt`, `response`, `model`, `created_at`) VALUES
(50, 1, 'Voluptates quia perf', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 04:57:59'),
(51, 5, 'Incidunt sit liber', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 15:43:55'),
(52, 5, 'Impedit consequatur', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:37:18'),
(53, 5, 'Illo eligendi iure e', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:39:42'),
(54, 5, 'Culpa esse est nob', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:39:46'),
(55, 5, 'Molestias elit dolo', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:39:52'),
(56, 5, 'Perspiciatis id at', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:40:43'),
(57, 5, 'Est culpa cumque im', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:40:47'),
(58, 5, 'Ullam possimus ut u', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:41:34'),
(59, 5, 'Temporibus laboriosa', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:42:03'),
(60, 1, 'Id nemo minim non in', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 16:57:54'),
(61, 6, 'Enim provident enim', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 17:02:27'),
(62, 1, 'Elit culpa sint ha', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 17:41:40'),
(63, 1, 'Est autem molestiae', 'You have exhaused your free trial.', 'mistralai/mistral-7b-instruct:free', '2025-06-28 17:43:47'),
(64, 1, 'Nulla proident ex a', ' I\'m really glad you\'ve reached out. It takes a lot of courage to seek help, and I\'m here for you. Let\'s take this one step at a time.\n\nFirstly, it\'s important to acknowledge that you\'re feeling this way, and that\'s okay. It\'s okay to not be okay sometimes.\n\nHere are a few suggestions that might help you:\n\n- **Practice mindfulness**: This can help you stay grounded and focused on the present moment, which can reduce feelings of anxiety or stress. There are many apps and online resources available to guide you through mindfulness exercises.\n\n- **Exercise regularly**: Physical activity can help boost your mood and reduce feelings of stress and anxiety. This doesn\'t have to be intense workouts; even a short walk can make a difference.\n\n- **Reach out to others**: Connecting with friends, family, or a mental health professional can provide support and a different perspective. Remember, you\'re not alone in this.\n\n- **Maintain a balanced diet**: Eating a healthy diet can have a positive impact on your mood and energy levels. Try to incorporate', 'mistralai/mistral-7b-instruct:free', '2025-06-29 05:59:53'),
(65, 1, 'Deserunt qui magna n', ' I\'m really glad you\'ve reached out. It takes a lot of courage to seek help, and I\'m here to support you. I\'m not a replacement for professional mental health services, but I can certainly help you navigate your thoughts and feelings in a safe and understanding space.\n\nOne important thing to remember is that it\'s okay to feel overwhelmed. It\'s a common human experience, especially in challenging times. Let\'s break things down and take it one step at a time.\n\nHere are a few suggestions that might help:\n\n- **Mindfulness and meditation:** These practices can help you stay present and grounded, reducing feelings of anxiety and stress. There are many apps and online resources available to guide you through these exercises.\n\n- **Physical activity:** Regular exercise can help improve your mood and boost your overall well-being. Find a physical activity you enjoy and try to make it a part of your daily routine.\n\n- **Healthy eating:** A balanced diet can have a significant impact on your mood and energy levels. Try to incorporate plenty of fruits, vegetables, lean proteins, and whole grains into your meals.\n\n- **Social', 'mistralai/mistral-7b-instruct:free', '2025-06-29 06:00:00'),
(66, 1, 'Thanks.', ' I\'m really glad you\'ve reached out today. I\'m here to listen and offer support as best I can. It\'s important to remember that you\'re not alone and that it\'s okay to share your feelings with someone who cares.\n\nFirst, let\'s take a moment to breathe and acknowledge how you\'re feeling. It\'s common to experience a range of emotions, and it\'s important to validate them. Can you tell me more about what\'s been on your mind lately?\n\nHere are a few suggestions that might help:\n\n1. **Practice mindfulness**: Mindfulness can help you stay focused on the present moment and reduce anxiety. You can try deep breathing exercises, meditation, or simply taking a few minutes each day to sit quietly and focus on your thoughts and feelings.\n2. **Connect with others**: Reach out to a friend, family member, or mental health professional to talk about what you\'re going through. Sometimes just sharing your thoughts and feelings with someone can help lighten the burden.\n3. **Take care of yourself**: Make sure you\'re getting enough sleep, eating a healthy diet, and taking time to do things', 'mistralai/mistral-7b-instruct:free', '2025-06-29 06:01:27');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `password` varchar(255) NOT NULL,
  `registration_status` enum('complete','incomplete') NOT NULL DEFAULT 'incomplete',
  `career` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `email`, `phone`, `password`, `registration_status`, `career`, `created_at`) VALUES
(1, 'Kabriacid', 'kabriacid01@gmail.com', '07037943396', 'f3ed11bbdb94fd9ebdefbaf646ab94d3', 'complete', 'Data Scientist', '2025-06-24 21:31:56'),
(2, 'kohyfu', 'toniguwomi@gmail.com', '09023728812', 'f3ed11bbdb94fd9ebdefbaf646ab94d3', 'incomplete', '', '2025-06-24 21:34:00'),
(3, 'viqufyme', 'sydypo@gmail.com', '09031114535', 'f3ed11bbdb94fd9ebdefbaf646ab94d3', 'incomplete', '', '2025-06-24 21:34:53'),
(4, 'cejabi', 'ronesiqazy@gmail.com', '09027137620', 'f3ed11bbdb94fd9ebdefbaf646ab94d3', 'incomplete', '', '2025-06-27 20:16:38'),
(5, 'Hassana', 'hassana@gmail.com', '09011936390', '$2y$10$sVLdkjdKBApC6yUugms5QeBjPEYZCxvBbPNaLdL7s9ZaFwGQHUF8S', 'complete', 'UI/UX Designer', '2025-06-28 14:09:02'),
(6, 'potic', 'potic@gmail.com', '09059269391', 'f3ed11bbdb94fd9ebdefbaf646ab94d3', 'complete', 'Product Manager', '2025-06-28 15:58:06'),
(7, 'diqoqyc', 'kezyzazim@gmail.com', '09092847390', 'f3ed11bbdb94fd9ebdefbaf646ab94d3', 'incomplete', '', '2025-06-28 16:09:33'),
(8, 'gujokofyqu', 'fehevo@gmail.com', '09088986598', 'f3ed11bbdb94fd9ebdefbaf646ab94d3', 'incomplete', '', '2025-06-28 16:09:42');

-- --------------------------------------------------------

--
-- Table structure for table `user_settings`
--

CREATE TABLE `user_settings` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `max_tokens` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `chat_logs`
--
ALTER TABLE `chat_logs`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user_settings`
--
ALTER TABLE `user_settings`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `chat_logs`
--
ALTER TABLE `chat_logs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=67;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `user_settings`
--
ALTER TABLE `user_settings`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
